const fs = require('fs');
const path = require('path');

function tsFolder() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  const y = d.getFullYear();
  const m = pad(d.getMonth() + 1);
  const day = pad(d.getDate());
  const hh = pad(d.getHours());
  const mm = pad(d.getMinutes());
  return `${y}${m}${day}-${hh}${mm}`;
}

function ensureDir(p){ fs.mkdirSync(p, { recursive: true }); }

function isSubPath(root, target) {
  const rel = path.relative(root, target);
  return !!rel && !rel.startsWith('..') && !path.isAbsolute(rel);
}

function createRunLogDir(base = 'logs') {
  const cwd = process.cwd();
  const dir = path.resolve(cwd, base, tsFolder());
  if (!isSubPath(cwd, dir)) throw new Error('Refuse to create logs outside workspace');
  ensureDir(dir);
  return dir;
}

function writeFileSafe(targetPath, content) {
  const cwd = process.cwd();
  const abs = path.resolve(cwd, targetPath);
  if (!isSubPath(cwd, abs)) throw new Error('Refuse to write outside workspace');
  ensureDir(path.dirname(abs));
  fs.writeFileSync(abs, content, 'utf8');
  return abs;
}

// Two-tier logging system
function createLogEntry(operation, details, sensitive = false) {
  const timestamp = new Date().toISOString();
  const logId = `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  
  // Summary log (safe to commit/share)
  const summary = {
    timestamp,
    logId,
    operation,
    status: details.status || 'info',
    summary: details.summary || '',
    files: details.files?.length || 0,
    errors: details.errors?.length || 0
  };
  
  // Detailed log (contains sensitive information)
  const detailed = {
    timestamp,
    logId,
    operation,
    ...details,
    sensitive: true
  };
  
  return { summary, detailed, logId };
}

function writeLogEntry(entry, basePath = 'logs') {
  const cwd = process.cwd();
  const summaryPath = path.resolve(cwd, basePath, `${entry.logId}-summary.md`);
  const detailedPath = path.resolve(cwd, basePath, `${entry.logId}-detailed.json`);
  
  // Write summary in markdown format (shareable)
  const summaryMd = `# ${entry.summary.operation} - ${entry.summary.status}

**Timestamp:** ${entry.summary.timestamp}
**Log ID:** ${entry.summary.logId}
**Files:** ${entry.summary.files}
**Errors:** ${entry.summary.errors}

## Summary
${entry.summary.summary}

---
*Generated by safe-ops-agent*
`;
  
  // Write detailed log in JSON format (sensitive)
  const detailedJson = JSON.stringify(entry.detailed, null, 2);
  
  writeFileSafe(summaryPath, summaryMd);
  writeFileSafe(detailedPath, detailedJson);
  
  return { summaryPath, detailedPath };
}

module.exports = { 
  createRunLogDir, 
  writeFileSafe, 
  createLogEntry, 
  writeLogEntry 
};

